/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 07-May-2020 17:41:35
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 106
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int lpsize = 106;
const int32_T lowpassfilter[106] = {
      -1416610,    -2643508,    -3846924,    -4686868,    -4823509,    -4014483,
      -2206342,      407214,     3383251,     6094922,     7858692,     8099983,
       6519450,     3215823,    -1274052,    -6041373,    -9976672,   -12017578,
     -11420411,    -7989620,    -2200937,     4827202,    11526746,    16210428,
      17474292,    14581064,     7726741,    -1889942,   -12236332,   -20840418,
     -25341932,   -24084807,   -16612710,    -3937003,    11513914,    26289831,
      36606727,    39202547,    32184418,    15675145,    -7906876,   -34034623,
     -56733398,   -69621055,   -67144141,   -45771492,    -4899093,    52736092,
     121247020,   192389525,   256834011,   305692873,   332023331,   332023331,
     305692873,   256834011,   192389525,   121247020,    52736092,    -4899093,
     -45771492,   -67144141,   -69621055,   -56733398,   -34034623,    -7906876,
      15675145,    32184418,    39202547,    36606727,    26289831,    11513914,
      -3937003,   -16612710,   -24084807,   -25341932,   -20840418,   -12236332,
      -1889942,     7726741,    14581064,    17474292,    16210428,    11526746,
       4827202,    -2200937,    -7989620,   -11420411,   -12017578,    -9976672,
      -6041373,    -1274052,     3215823,     6519450,     8099983,     7858692,
       6094922,     3383251,      407214,    -2206342,    -4014483,    -4823509,
      -4686868,    -3846924,    -2643508,    -1416610
};
